version: "3.9"

services:
  web:
    build: .
    container_name: docupath_web
    env_file: .env
    volumes:
      - ./django:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: docupath_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/staticfiles
      - ./media:/media
      - ./certs:/etc/ssl/certs:ro
    depends_on:
      - web
    restart: always
