version: "3.9"

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      VITE_DEV_MODE: "false"

  vite:
    build:
      context: .
      dockerfile: docker/vite.Dockerfile
    container_name: container_vite
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./django:/django
      - ./staticfiles:/django/staticfiles
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
